[build-system]
requires = ["uv_build>=0.10.12,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."

[project]
name = "baccy"
version = "0.1.0"
description = "Permanent backup daemon for media and other assets"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Tom Ritchford", email = "tom@swirly.com" },
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.0",
    "jinja2>=3.1.6",
    "pydantic>=2.13.5",
    "reccy",
    "simpleeval>=1.0.6",
    "tomlkit>=0.15.1",
    "tyro>=1.0.16",
]

[project.urls]
Repository = "https://github.com/rec/baccy"

[project.scripts]
baccy = "baccy.__main__:main"

[tool.uv.sources]
reccy = { path = "../reccy", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pyupgrade>=3.21.2",
    "ruff>=0.16.7",
    "ty>=0.0.80",
]

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["B", "E", "F", "I"]
