[build-system]
requires = ["uv_build>=0.10.12,<0.11"]
build-backend = "uv_build"

[project]
name = "baccy"
version = "0.1.0"
description = "Permanent backup daemon for media and other assets"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Tom Ritchford", email = "tom@swirly.com" },
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.5",
    "reccy",
    "tyro>=1.0.16",
]

[project.urls]
Repository = "https://github.com/rec/baccy"

[tool.uv.sources]
reccy = { path = "../reccy", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pyupgrade>=3.21.2",
    "ruff>=0.16.7",
    "ty>=0.0.80",
]

